service: "default"
runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
inbound_services:
  - warmup
env_variables:
  SERVICE_CALLER_SECRET_NAME: "service-caller-sa-key"
